### ISSUE TITLE
Ownership pool can not start Sojourn pool

### ISSUE THREAD

**Issue by fishcakez** [elixir-ecto/db_connection#106]
The Ownership pool starts its internal pool via the Watcher, and Sojourn starts its internal pool via the Watcher. The Watcher blocks when starting an internal pool so can't receive the request from Sojourn to start its internal pool as it blocking starting the Sojourn pool itself (Ownership's internal pool).

**Comment by josevalim** [comment]
FWIW, I am completely fine with saying we only work with poolboy if fixing it is going to be a big hassle.

**Comment by fishcakez** [comment]
I am happy to force poolboy too. This isn't an issue for Ecto because poolboy will always be there.

**Comment by michalmuskala** [comment]
:+1: for ownership pool working only with poolboy. Should we remove the ability to specify the "inner" pool for ownership pool altogether?

**Comment by michalmuskala** [comment]
I will close the issue given we'll be moving away from poolboy and sojurn in 2.0
