### ISSUE TITLE
How to avoid starting Sojourn?

### ISSUE THREAD

**Issue by sauvainr** [elixir-ecto/db_connection#109]
Hi, we are using a module using poolboy based on this project, I notice Sojourn process being started anyway.
From https://github.com/elixir-ecto/db_connection/blob/188e99191df55ffe1e5927637c79a8c638bc1117/lib/db_connection/app.ex#L10

Is it intended? How to prevent Sojourn pool to start if using poolboy? Could we have the pool module as parameter or so instead?

Thanks

**Comment by michalmuskala** [comment]
It's not starting sojurn pool, it's only a supervisor for supervising sojurn pools if they are started - this shouldn't cause any issues.

**Comment by fishcakez** [comment]
> Could we have the pool module as parameter or so instead?

The already exists, `pool: DBConnection.Poolboy`:
https://github.com/elixir-ecto/db_connection/blob/188e99191df55ffe1e5927637c79a8c638bc1117/lib/db_connection.ex#L539-L540
In Ecto this is the default pool so don't need to set it there.

**Comment by sauvainr** [comment]
Thanks for the quick answer, so basically the Sojourn supervisor is running idle when using poolboy?

Not an issue but surprising when troubleshooting db connection pools.

**Comment by fishcakez** [comment]
> Thanks for the quick answer, so basically the Sojourn supervisor is running idle when using poolboy?

Its empty yes.
