### ISSUE TITLE
Add a way to disable connect exception sanitisation

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/db_connection#120]
It sometimes might be problematic when all details of exceptions are erased and once tries to debug some issue. I agree that the sanitisation should be there by default, but it should be possible to disable it with an option during a debugging session.

**Comment by fishcakez** [comment]
I think we can improve the message instead or as well. The exception type and stacktrace is still there so likely they can debug but because it says information was removed they get lazy.

**Comment by michalmuskala** [comment]
I think we should have a `enable_unsafe_errors` setting or something like that. Additionally when it's set we should print a warning.

**Comment by josevalim** [comment]
Closing in favor of #161.
