### ISSUE TITLE
DBConnection.run should fail if the connection state before and after are not the same

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/db_connection#122]

**Comment by josevalim** [comment]
The question is if we should ALWAYS do this or only on certain cases.

**Comment by fishcakez** [comment]
This is a tricky one, it might be we should provide the functions and drivers build their own `run` from lower level functions. Currently every function called in the context of a `run` except transaction functions. This would no longer map as we only care about the checkout -> checkin change

**Comment by josevalim** [comment]
For now we are inclined to do this on the side. But we still need to check the disconnect behaviour with status.

**Comment by josevalim** [comment]
CLosing in favor of #145.
