### ISSUE TITLE
Remove handle_info

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/db_connection#133]
@fishcakez what is the rationale to remove handle_info?

Supporting it is straight-forward and if we remove it one of our examples (TCP connections) will no longer work.

**Comment by fishcakez** [comment]
@josevalim we no longer call it, so the example should be broken. Sockets are forced to be passive. This means we should be able to remove `checkout/1` and `checkin/1` as they would be no-ops.

**Comment by josevalim** [comment]
Closing in favor of #134
