### ISSUE TITLE
Repeated timeout of the connection

### ISSUE THREAD

**Issue by MeerKatDev** [elixir-ecto/db_connection#205]
The DB connection works well when there's a request to resolve, but this message

`[error] MyXQL.Connection (#PID<0.389.0>) failed to connect: ** (DBConnection.ConnectionError) timeout`

keeps appearing on the console. How do I stop it?

**Comment by josevalim** [comment]
Please provide more information on how and when this issue happens, versions or even a mechanism to reproduce, otherwise there isn’t much we can do help. But typically, this happens because of wrong credentials or wrong configuration, so we can’t connect to the server.

**Comment by josevalim** [comment]
Please let us know if you have more information and we will gladly reopen it. Thank you!
