### ISSUE TITLE
DBConnection.ConnectionError sometimes raise, sometimes returned

### ISSUE THREAD

**Issue by jvf** [elixir-ecto/db_connection#208]
Due to a crash of the database server I see lots of (concurrent) queries failing with `%DBConnection.ConnectionError{message: "connection not available and request was dropped from queue ...}`. In some of the cases the ConnectionError is returned as an `:error` tuple and in other cases the error is raised by DBConnection. Is this intended by behaviour? If so, what does returning an `:error` tuple vs raising indicate?

**Comment by josevalim** [comment]
How are you using DBConnection? The error tuple is usually controlled by whatever is wrapping DBConnection. So if you are using Ecto, the tuple is for validations and so on.

**Comment by jvf** [comment]
I am using DBConnection through [Xandra](https://hex.pm/packages/xandra). 

> The error tuple is usually controlled by whatever is wrapping DBConnection.

Do I understand you correctly: DBConnection always throws, i.e. if I see it wrapped in en error tuple this has to come Xandra?

**Comment by josevalim** [comment]
Exactly!

**Comment by jvf** [comment]
Thank you for explaining!
