### ISSUE TITLE
DBConnection.ConnectionPool.handle_info/2 :DOWN handling

### ISSUE THREAD

**Issue by factorijnul** [elixir-ecto/db_connection#214]
Hi! My team is hitting this error consistently:
> FunctionClauseError: no function clause matching in DBConnection.ConnectionPool.handle_info/2
>   File "lib/db_connection/connection_pool.ex", line 34, in DBConnection.ConnectionPool.handle_info/2
>   File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
>   File "gen_server.erl", line 711, in :gen_server.handle_msg/6
>   File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3

This message seems to be causing it:
> {:DOWN, #Reference<0.3236932737.498073604.46302>, :process, #PID<0.9847.3>, :shutdown}

It appears that the connection pool doesn't ever expect a :DOWN message, and it's not clear to us why it would be receiving such a message. Any advice on how to track this down would be greatly appreciated. Thanks!

**Comment by josevalim** [comment]
Can you tell us a bit more about the issue? When does it happen? Which version are you using? Can you reproduce it consistently? Etc.

**Comment by factorijnul** [comment]
Versions:
{:phoenix_ecto, "~> 4.1"},
{:ecto_sql, "~> 3.3"},
{:postgrex, "~> 0.15"},

I'll try and round up some more context, but as of right now I can't reliably reproduce locally

**Comment by datafoo** [comment]
Would you please share your findings?
