### ISSUE TITLE
How to properly catch overloaded pool errors?

### ISSUE THREAD

**Issue by deadtrickster** [elixir-ecto/db_connection#217]
Hi, 

When checkout timeout happens DBConnection.ConnectionError raised. However it also raised in several other places and even in tests assertion uses regex for the message: ~r"connection not available and request was dropped from queue after \d+ms". 

Should I use same regex matching?

**Comment by josevalim** [comment]
Yes. I think introducing another exception for this at this point would unfortunately be a breaking change. :/

**Comment by qcam** [comment]
Could we maybe introduce metadata to the existing exception? Something like `[reason: :checkout_timeout]`?

**Comment by josevalim** [comment]
That could be handy, yes!

**Comment by qcam** [comment]
👍 Awesome, I can prepare a PR.

**Comment by deadtrickster** [comment]
@qcam ping
