### ISSUE TITLE
System.stacktrace deprecation warnings

### ISSUE THREAD

**Issue by altdsoy** [elixir-ecto/db_connection#225]
Hello all,

With elixir 1.11 i'm getting a lot of warnings when compiling this package.
When I look into the `mix.exs` file for the Elixir version supported it appears it's from 1.7 onwards.
According to this https://elixir-lang.org/blog/2018/07/25/elixir-v1-7-0-released/ , `__STACKTRACE__` was introduced in 1.7..

So isn't there an opportunity to replace all the `System.stacktrace()` with the new `__STACKTRACE__` syntax?
I can do it right now if you want..

However I might missed something else so I didn't want to pollute with a PR without having a confirmation about the reason `System.stacktrace/0` is still used..

Cheers!!

**Comment by josevalim** [comment]
It has already been fixed, I just need to do a new release. I will do so tomorrow. :)

**Comment by altdsoy** [comment]
You rock José!

Don't know how you're able to find so much time responding almost instantly and in so many fronts (I mean how many libraries/repos are you maintaining?)!
It really gives me a good feeling programming with Elixir because of you guys!

Really keep up the good work!!

i hope I'll be able to give back at one moment..

**Comment by josevalim** [comment]
Released! <3
