### ISSUE TITLE
Different login failure error is printed in console [windows, otp 20, elixir 1.9] [linux, otp 23, elixir 1.11]

### ISSUE THREAD

**Issue by mjaric** [elixir-ecto/db_connection#230]
This is more question than an issue, I'm working on TDS deriver and noticed that same code behaves differently when OTP/elixir versions are not the same

Below is image, same test cases:
- LEFT is windows, OTP 20, Elixir 1.9. Logged message is `(Tds.Error) Line 1 (Error 18456): Login failed for user 'sa'`
- RIGHT is linux, OTP 23, Elixir 1.11. Logged message is `(Tds.Error) tcp connect: econnrefused`

![win-nix-dissference](https://user-images.githubusercontent.com/327155/100777067-9ab58400-3405-11eb-995c-89c2f1bdde82.png)

Is this something related to db_connection or erlang?

**Comment by mjaric** [comment]
For note, [this](https://github.com/livehelpnow/tds/blob/222d95c860fcaf8864711e0624337d5c018f6a6b/test/login_test.exs#L25) is test cases that is logged above

**Comment by josevalim** [comment]
There are so many changes in environment that it is hard to know. I would try making the parameters as close as possible, including OS, and see how it changes things. You should be able to run Elixir v1.9 with OTP 23 (even if not officially supported).

**Comment by mjaric** [comment]
I'm using asdf, so it shouldn't be that hard. I'll let you know when I narrow down when this occurs

**Comment by mjaric** [comment]
Ah, this is totally my fault! It is test environment setup. Funny thing is that only this test case was affected.

Sorry for noise!

Thanks!
