### ISSUE TITLE
Telemetry event for capturing DBConnection.ConnectionError

### ISSUE THREAD

**Issue by polvalente** [elixir-ecto/db_connection#234]
Is there any way to measure through telemetry if the database keeps dropping connections with DBConnection.ConnectionError?

I noticed that the `drop` private function in `deps/db_connection/lib/db_connection/connection_pool.ex` does print a custom inspect whenever the connection is dropped due to timeout. Maybe that could be a place to add the event? Or is there a better place in :ecto or :ecto_sql to do so?

I could work on the PR myself given the right direction!

Thanks in advance

**Comment by josevalim** [comment]
We can definitely add a telemetry event for that. And likely one for when connections are established too.

**Comment by polvalente** [comment]
@josevalim I was reading #228 and maybe adding another message for timeouts could also be a way to handle this. What do you think?

**Comment by josevalim** [comment]
That also sounds good to me! PRs are welcome!

**Comment by polvalente** [comment]
> That also sounds good to me! PRs are welcome!

Ok then! I'll try to come up with _something_

**Comment by polvalente** [comment]
Resolved in #236
