### ISSUE TITLE
Telemetry event for all connection errors

### ISSUE THREAD

**Issue by akash-akya** [elixir-ecto/db_connection#239]
### Use case

We have an application which connects to multiple MySQL databases. As of now, whenever there is a connection error, all we get is a generic error log, like `MyXQL.Connection (#PID<*.*.*>) failed to connect: ** (DBConnection.ConnectionError) connection refused`. This makes debugging difficult for us. We like to have error logs with repo information.

### Change proposal

I noticed we already have [telemetry events](https://github.com/elixir-ecto/db_connection/pull/236/). We can use this to log duplicate error message with repo information fetched from telemetry metadata. But looks like currently events are only emitted when there is a checkout attempt. So not all connection errors emit the event (such as connect attempt in background when app starts).

What you think of emitting event for every "connect" failure?

**Comment by josevalim** [comment]
Please do investigate. However, if you want to have repository information, it is unlikely this would be a DBConnection feature. Perhaps the easiest route to start is by changing MyXQL to include more information in the error messages (at least hostname+port).

**Comment by akash-akya** [comment]
We are already passing all `opts` in the telemetry event right? Thought of just logging `opts[:repo]`. No changes required to db_connection for this, `opts` is still opaque. Only change is - emitting telemetry event [here](https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection/connection.ex#L103) instead of in the holder. 

> easiest route to start is by changing MyXQL to include more information in the error messages (at least hostname+port).

Agree. Will look into this first 

Thanks

**Comment by josevalim** [comment]
Ah, if the error is coming from DBConnection then changing MyXQL to include more information won't work. The fix has to be here, although we choose to not allow telemetry events inside the connections themselves. 🤔 We could use the current connection listeners though... maybe include a connection_failure event that includes the exception? And then include more information, if possible, in the exception?

**Comment by akash-akya** [comment]
> if the error is coming from DBConnection then changing MyXQL to include more information won't work

I thought you meant the exception message from myxql should contain more information, so when DBConnection logs it with `Exception.format_banner` it contains the required information. In fact MongoDB lib [already does this](https://github.com/kobil-systems/mongodb/blob/062e9b58939e56efbde243a922b76abb9e644a0c/lib/mongo/protocol.ex#L151) for most of the errors.

> We could use the current connection listeners

Previously I thought of it. But dropped it thinking that since we dont really need the connection, and thinking it like "telemetry event" made more sense. Anyway I will look into that as well.

**Comment by akash-akya** [comment]
Opened an [issue](https://github.com/elixir-ecto/myxql/issues/135) at MyXQL for changing error message and its already is addressed there. 

Closing in favor of that.
