### ISSUE TITLE
Dyno load (CPU load) spikes with db_connection >= 2.2.2

### ISSUE THREAD

**Issue by jesseahouser** [elixir-ecto/db_connection#265]
#### Issue Description
Following some dependency package upgrades, our team observed dyno load spikes a few times per day. Prior to these upgrades, we have experienced years of consistent, normal dyno load levels.

#### Context and Details
This Elixir app is hosted in a Heroku Private Space, and dyno load is their measure of CPU load (https://devcenter.heroku.com/articles/metrics#dyno-load). Dyno load maxes out for approximately 15-30 minutes with each spike, then returns to normal load on its own. We are running two web servers, and the spikes affect both, are unsynchronized, and are not dependent on traffic. This Elixir app maintains connections to three different Postgres databases with a pool size of 40 each. 

#### To Reproduce
We began an investigation to narrow down which package(s) might be related to the issue. This revealed that the spikes:
- occur when using db_connection >= 2.2.2
- do not occur when using db_connection <= 2.2.1

We can reproduce this behavior by changing only the db_connection version to >= 2.2.2 in `mix.lock`.

#### Screenshot
<img width="2517" alt="dyno_load_db_connection" src="https://user-images.githubusercontent.com/78939437/175791858-04a3c664-f4f5-49ad-aff8-9c8301780fad.png">

**Comment by josevalim** [comment]
2.2.2 contains only a commit that makes sure all connections are pinged within an idle_interval. You can see the initial report here: https://github.com/elixir-ecto/db_connection/pull/216

Are you sure that you need a pool of 40 connections? If they are not being used, it means that indeed you will be pinged every second. You can consider either increasing the idle interval or decreasing the pool size. We can also add an idle threshold configuration if you really believe the pool size is justified.

**Comment by josevalim** [comment]
Also: awesome job on isolating the issue and great report!
