### ISSUE TITLE
Support for Azure Redirect Connection Policy

### ISSUE THREAD

**Issue by user20230119** [elixir-ecto/db_connection#295]
I have an issue with Elixir TDS https://github.com/elixir-ecto/tds/issues/150 where containers on Azure connect to Azure SQL databases with a redirect connection policy.

Normally, TDS connects to the SQL server on port 1433 and will send all queries on port 1433.

With redirect,
- TDS connects to the SQL server on port 1433
- SQL Server redirects TDS to another hostname and port in range 11000 to 11999
- TDS connects to the other hostname and port
- TDS sends all queries to the other hostname and port
- TDS pings the other hostname and port to keep the connection alive
- after two minutes, Azure SQL closes the connection on port 1433

When the connection on port 1433 closes,
- the DBConnection GenServer process terminates with `:tcp_closed`
- the other connection that was kept alive on the other hostname and port also closes

Ecto queries fail if the query is
- sent to a TDS connection in the pool before port 1433 closes
- executed after port 1433 closes

Is there a setting to keep the other port open when port 1433 closes?

**Comment by josevalim** [comment]
TDS is the best place to discuss this, as DBConnection is not the one establishing the actual TCP connections.
