### ISSUE TITLE
Is it possible to close and reconnect a DBConnection regularly?

### ISSUE THREAD

**Issue by zche-theScore** [elixir-ecto/db_connection#305]
I skimmed through the code and it looks like that each connection in the connection pool is a long live connection, pinging regularly.

In my case, I would like to have each connection closes and immediately reconnects regularly, instead of pinging. (Another perspective is to add a connection to the pool and remove one in a FIFO sequence)

Is there already a configuration to do it? I didn't find anything fruitful through the docs and the code.

**Comment by josevalim** [comment]
No, there is no such option in DBConnection. Perhaps you can use a library like poolboy to achieve what you want. :)
