### ISSUE TITLE
Guidance on handling closed connections

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/db_connection#315]
👋 

I wonder if it's possible to gracefully reconnect once the underlying adapter's connection is detected to be closed to avoid `:closed` errors on user queries (DBConnection.query / DBConnection.execute)? For example, maybe we could use [`:inet.monitor/1`](https://www.erlang.org/doc/apps/kernel/inet.html#monitor/1) from the adapters? Maybe it could be possible to let the adapters handle_info the DOWN messages?

Related Ch issues / PRs: https://github.com/plausible/ch/issues/210, https://github.com/plausible/ch/pull/211

**Comment by josevalim** [comment]
If I understand correctly, the issue is that DBConnection is not very kind to changing the connection once a query starts, right? So we would need to add a mechanism that allows the adapter to say: "try again with another connection, I am going away"?

**Comment by ruslandoga** [comment]
I think we can already do this without "telling" DBConnection like in https://github.com/plausible/ch/pull/211. 

> So we would need to add a mechanism that allows the adapter to say: "try again with another connection, I am going away"?

Do you mean a new connection entirely, or another connection from the pool? The approach I linked above is about a new connection entirely, and that seems to work but kind of feels like the reconnection can happen earlier, not on ping or query attempt. If you mean another connection from the existing pool, they might be disconnected as well.

I was thinking more in terms of:
- connection is idle, it's some time away from the next ping and there is no user query incoming
- underlying TCP connections gets closed
- connection gets DOWN message from the monitor and asks DBConnection to reconnect (via {:disconnect, conn})
- error is logged, making it clear that there might be some instability in the user's system
- the next arriving query gets a connected connection

What seems to be happening right now in Ch is the following:
- connection is idle, it's some time away from the next ping and there is no user query incoming
- underlying TCP connections gets closed
- DBConnection query arrives, uses a closed connection, gets :closed` error back, disconnects, users gets an error that could've been avoided

For some additional context, I think it might be similar to https://github.com/sneako/finch/issues/272

**Comment by josevalim** [comment]
> I was thinking more in terms of

Makes sense! I think this can all be implemented in the connection then, no? Without a need to change DBConnection? You should be able to receive the `:inet.monitor` messages in your connection process.

**Comment by ruslandoga** [comment]
I'll try but I think [`info` messages](https://github.com/elixir-ecto/db_connection/blob/c6dcdf92a205e02da2468258085bc0792d39df09/lib/db_connection/connection.ex#L264-L339) are not "propagated" to the adapter. But maybe one of the existing {:DOWN,...} handlers would work out of the box.

**Comment by ruslandoga** [comment]
I tried it out in https://github.com/plausible/ch/pull/212 and the unmatched info messages seem to be [ignored:](https://github.com/elixir-ecto/db_connection/blob/c6dcdf92a205e02da2468258085bc0792d39df09/lib/db_connection/connection.ex#L333-L339)

```
12:29:27.338 [info] Ch.Connection (#PID<0.1827.0>) missed message: {:DOWN, #Reference<0.854798976.1477443587.123761>, :port, #Port<0.4>, :normal}

12:29:27.338 [info] Ch.Connection (#PID<0.1827.0>) missed message: {:DOWN, #Reference<0.854798976.1477443587.123863>, :port, #Port<0.5>, :normal}
```

**Comment by josevalim** [comment]
Good catch, so let's proxy those if the connection has defined a `handle_info` callback (which will be optional). Can you please send a PR? Otherwise let me know and I will tackle it.
