### ISSUE TITLE
Thoughts on a min/max for number of connections?

### ISSUE THREAD

**Issue by atonse** [elixir-ecto/db_connection#318]
Apologies if this is an existing discussion (I searched for "minimum" and found nothing).

I'm writing this to ask if the Ecto team has considered having a min/max number of configured connections for this pool.

This would allow us when we're using elastic/serverless databases (Aurora, Neon, etc) to also bring down the number of connections when there is less load/connections are idle.

Right now, we had a max of 40 connections but when we made our database smaller, even though most of those connections were idle due to our traffic, they weren't getting "released" causing us to not be able to connect to our database using third party tools.

If we can have the option of a minimum and maximum number of connections (with an idle_disconnection), then it would allow the number of connections in the pool to also scale.

**Comment by josevalim** [comment]
Latest Ecto supports multiple pools and Elixir v1.18 will allow you to resize those pools, so you will be able to achieve what you want. However, keep in mind you may be asking for trouble:

1. PostgreSQL connections in particular are expensive to establish. So if you have spikes, by the time you are done establishing connections, you may have already overloaded the existing ones

2. "they weren't getting "released" causing us to not be able to connect to our database using third party tools." you are now opening yourself to the opposite issue: your third party tools will be using these connections and now your app won't be able to scale if you need them

There is also the possibility you don't need 40 connections and you are over provisioning your app. So tread carefully :)

**Comment by atonse** [comment]
@josevalim thank you for your detailed response.

It turns out this was entirely my fault (our Tailscale bastion was down, which is why we couldn't connect to the database). I was conflating this with the errors in Appsignal we often get during deploys about how we're running out of connections (which is temporary because we double the number of connections to launch the new copy of the app before we take down the old copy).

We ended up bringing down the number of connections overall anyway (we were definitely over-provisioning for when our app was used during the pandemic, but never actually fixed the pool size in the 2 years since!)
