### ISSUE TITLE
Allow configuring pool_size with env vars

### ISSUE THREAD

**Issue by whoward** [elixir-ecto/db_connection#61]
It would be great if we could tune the pool size using an environment variable - it doesn't currently seem to work.  We can do this with other configuration parameters like `url` in the form of `{:system, "ENV_VAR_NAME"}`

**Comment by fishcakez** [comment]
Hi @whoward. DBConnection is very low level and doesn't support any application or system env, it only does explicit keyword list options. Likely you want to open this in ecto where the configuration for `url` etc is handled. You may also be interested in https://github.com/phoenixframework/phoenix/issues/1730.

**Comment by whoward** [comment]
ok i'll move this to ecto - sadly you can't use System.get_env in the configuration file because its 'baked in' at compile time, hence the `{:system, "ENV_VAR_NAME"}` pattern's purpose for existing

**Comment by fishcakez** [comment]
@whoward do you mean baked in at release built time? This is not quite the same as compile time, as it will work when using `mix run` etc.

**Comment by whoward** [comment]
yeah release build time :) using exrm or distillery

**Comment by michalmuskala** [comment]
AFAIK ecto supports the `{:system, "VAR_NAME"}` idiom for the url option since a long time

**Comment by fishcakez** [comment]
Discussion moved here: https://groups.google.com/forum/#!topic/elixir-ecto/BiWJvWbUDc0

@michalmuskala this is about doing a similar thing to `:url` for `:pool_size`
